# Generated by Django 4.2.1 on 2023-06-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='Slug',
        ),
        migrations.AlterField(
            model_name='events',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
